FROM resin/rpi-raspbian
MAINTAINER github@vanefferenonline.nl

COPY *.sh /opt/dropbox_uploader/
RUN mkdir -p /config && mkdir -p /workdir

VOLUME /config /workdir

WORKDIR /workdir

ENTRYPOINT ["/opt/dropbox_uploader/dropbox_uploader.sh", "-f", "/config/dropbox_uploader.conf"]
